### PR TITLE
Conversion gnucap to qucs format

### PR DESCRIPTION
**Pull request by oxmon-2500**
- translate2qucs program added which replaces script-convertion
- <Qucs dataset> header moved closer to dataset

### CODE REVIEW

**Comment by felix-salfelder** [comment]
On Mon, May 11, 2020 at 04:43:24AM -0700, Szymon Blachuta wrote:
> - translate2qucs program added which replaces script-convertion
> - &lt;Qucs dataset&gt; header moved closer to dataset

Thanks. The C++ code writing the qucs dataset belongs to s_out.cc.  I am
not doing anything about it only because there are more pressing things.
I appreciate the help!

Future s__out.cc will be pluggable (and I wish it already was), the code
will have to be moved from s_out.cc into an output plugin, and there
will be no more need for an s_tr*.cc copy anymore.

In the meantime... we could change the default for postproc_tr to your
C++ implementation (line 104), if you like. But move the code to contrib
and leave the override in, please.

**Comment by oxmon-2500** [comment]
Changes done.
It was thought anyway as a temporary solution to have a fast conversion out of box

**Comment by felix-salfelder** [comment]
On Tue, May 12, 2020 at 01:12:35AM -0700, Szymon Blachuta wrote:
> Changes done.
> It was thought anyway as a temporary solution to have a fast conversion out of box

Agree. I wonder if it's less work to complete s_tr_out.cc (cf "out"
branch). I pasted some of your code there, it will move to out_qucs.cc
eventually.

**Comment by oxmon-2500** [comment]
I didn't succeed with the s_tr.cc/s_tr_out.cc implementation. I need some time to become familiar with the architecture of gnucap/gnucsator. I would say to make the current PR to a release and I try it in the meanwhile in a different branch

**Comment by felix-salfelder** [comment]
On Wed, May 13, 2020 at 08:57:26AM -0700, Szymon Blachuta wrote:
> I didn't succeed with the s_tr.cc/s_tr_out.cc implementation. I need
> some time to become familiar with the architecture of
> gnucap/gnucsator. I would say to make the current PR to a release and
> I try it in the meanwhile in a different branch

output works for transient now. it breaks the postprocessing hook,
because of the format changed. maybe not too bad?

**Comment by felix-salfelder** [comment]
this merge request looks obsolete now. please reopen if it is not.

**Comment by oxmon-2500** [comment]
Thank you for modifications. The transient simulation output is now in qucs format. The steps to be done now:
- issue a general \<Qucs Dataset\> on start of outputfile
- new/changed arguments: -i inpNetFile -o outputFile -b ignore -g ignore
After this gnucsator can be called directly from qucs

**Comment by felix-salfelder** [comment]
On Sun, May 31, 2020 at 08:07:09AM -0700, Szymon Blachuta wrote:
> Thank you for modifications. The transient simulation output is now in qucs format. The steps to be done now:
> - issue a general <Qucs Dataset> on start of outputfile
> - new/changed arguments: -i inpNetFile -o outputFile -b ignore -g ignore
> After this gnucsator can be called directly from qucs

this is about getting rid of the gnucsator.sh wrapper script, right?

if so, I know what you are talking about. thanks for the summary!

**Comment by oxmon-2500** [comment]
I will approach this in next time and make a new PR.

**Comment by felix-salfelder** [comment]
On Mon, Jun 01, 2020 at 12:36:49AM -0700, Szymon Blachuta wrote:
> I will approach this in next time and make a new PR.

both of them must move to gnucsator.rc. The <Dataset> is just a `message
[1].

need to clarify the relation to gnucap-custom. could either depend on
it, or just merge the two and add the rest -- less maintenance work.

[1] https://codeberg.org/gnucap/gnucap-custom/src/branch/master/c_message.cc

**Pull request closed without merging**
